batchsize: 8
iteration: 450000
iteration_decay_start: 400000
seed: 0
display_interval: 100
progressbar_interval: 100
snapshot_interval: 10000
evaluation_interval: 5000

models:
  generator:
    fn: gen_models/resnet_256.py
    name: ResNetGenerator
    args:
      dim_z: 128
      bottom_width: 4
      ch: 32
      n_classes: 143


  discriminator:
      fn: dis_models/snresnet_256.py
      name: SNResNetProjectionDiscriminator
      args:
        ch: 32
        n_classes: 143

dataset:
  dataset_fn: datasets/imagenet_dog_and_cat.py
  dataset_name: ImageNetDogAndCatDataset
  args:
    path: datasets/image_list_dog_and_cat.txt
    size: 256
    resize_method: bilinear
    augmentation: True

adam:
  alpha: 0.0002
  beta1: 0.0
  beta2: 0.9

updater:
  fn: updater.py
  name: Updater
  args:
    n_dis: 5
    n_gen_samples: 16
    conditional: True
    loss_type: hinge
